### PR TITLE
Add declaration file for typescript

### PR DESCRIPTION
**Pull request by somibuon**

### CODE REVIEW

**Comment by ladifire** [comment]
@somibuon Please update repo to check new errors of your TS definition

**Comment by somibuon** [comment]
I tried but didn't see any errors, could you please provide which case causing errors

**Comment by ladifire** [comment]
@somibuon 
Screenshot from 2021-01-19 15-25-01

Edit "@media" to any thing not cause error or warning??

Screenshot from 2021-01-19 15-24-45

"a" property still recornized
"borderRadius" can not use with number

**Comment by somibuon** [comment]
ok i will update it soon

**Pull request merged**
